" add recursive search
set path+=**

" match ErrorMsg '\%>80v.\+'
set ch=3    " Height of command line
set number "line numbers
set mousehide " Hide the mouse when typing text
set smartindent
set backspace=indent,eol,start
set expandtab tabstop=2
set shiftwidth=0

" Naughty Dog standards
if $NDIBIN == "c:/ndibin"
  set shiftwidth=4
  set softtabstop=4
  set tabstop=4
  set encoding=utf-8

  let g:maxd_NDGame = $GAMENAME
  let g:maxd_NDBranch = $GAMEBRANCH
  let g:maxd_NDPath = 'c:\perforce\' . g:maxd_NDBranch
  let &path = ""
  let &path .= ',' . g:maxd_NDPath . '\shared\src\'
  let &path .= ',' . g:maxd_NDPath . '\shared\src\**'
  let &path .= ',' . g:maxd_NDPath . '\' . g:maxd_NDGame . '\src\'
  let &path .= ',' . g:maxd_NDPath . '\' . g:maxd_NDGame . '\src\**'

  exec ":cd " . g:maxd_NDPath
endif

" folding options: group by indentation, ignore comments
set foldmethod=indent
set foldignore=

set cursorline

au GUIEnter * simalt ~x " maximize on startup


if has('gui_running')
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar
  set guioptions-=r  "remove scrollbar
  set guioptions-=L  "remove scrollbar
  if has('gui_win32')
    " better than Inconsolata, liberation mono (this is what sublime uses)
    set guifont=Consolas:h12
    colorscheme molokai
  endif
else
endif


set hlsearch " Switch on search pattern highlighting.
syntax on

" the wiki said these disable bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

set wrap
" set nowrap

set ttimeoutlen=10
let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>

" basically control c
vmap <Leader>y "+y

" basically control v
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

nnoremap <Leader>q :q<CR>

"Use TAB to complete when typing words, else inserts TABs as usual.
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
:inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>
:set dictionary="/usr/dict/words"


" show line numbers during :Explore
let g:netrw_bufsettings = 'noma nomod nu nowrap ro nobl'


" ignore annoying ^M carriage returns ( /r/n )
match Ignore /\r$/

" fk it
set syntax=c

" avoid seeing annoying .swps in explorer/netrw. Note that you need to create
" C:\Users\Nate\.vim\_backups
" C:\Users\Nate\.vim\_swaps
set backup                    " keep a backup file
set backupdir=~/.vim/_backups " store backups here
set directory=~/.vim/_swaps   " store swap files here

