" add recursive search
set path+=**

" match ErrorMsg '\%>80v.\+'
set ch=3    " Height of command line
set number "line numbers
set mousehide " Hide the mouse when typing text
set smartindent
set backspace=indent,eol,start
set expandtab tabstop=2
set shiftwidth=0

" folding options: group by indentation, ignore comments
set foldmethod=indent
set foldignore=

set cursorline

au GUIEnter * simalt ~x " maximize on startup


if has('gui_running')
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar
  set guioptions-=r  "remove scrollbar
  set guioptions-=L  "remove scrollbar
  if has('gui_win32')
    " better than Inconsolata, liberation mono (this is what sublime uses)
    set guifont=Consolas:h12
    colorscheme molokai
  endif
else
endif


set hlsearch " Switch on search pattern highlighting.
syntax on

" the wiki said these disable bells
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

set wrap
" set nowrap

set ttimeoutlen=10
let mapleader = "\<Space>"
nnoremap <Leader>w :w<CR>

" basically control c
vmap <Leader>y "+y

" basically control v
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P

nnoremap <Leader>q :q<CR>

"Use TAB to complete when typing words, else inserts TABs as usual.
function! Tab_Or_Complete()
  if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
    return "\<C-N>"
  else
    return "\<Tab>"
  endif
endfunction
:inoremap <Tab> <C-R>=Tab_Or_Complete()<CR>
:set dictionary="/usr/dict/words"


" show line numbers during :Explore
let g:netrw_bufsettings = 'noma nomod nu nowrap ro nobl'


" ignore annoying ^M carriage returns ( /r/n )
match Ignore /\r$/

" set unknown filetypes to read with c
set syntax=c

" stomp over some existing filetypes to read with c instead
autocmd BufNewFile,BufRead *.hlsl,*.fx set syntax=c


" https://stackoverflow.com/questions/21010029/hiding-swp-files-in-the-default-vim-file-browser
" Note that you need to create
" C:\Users\Nate\.vim\_backups
" C:\Users\Nate\.vim\_swaps
set backup                    " keep a backup file
set nobackup                  " but like... dont?
set backupdir=~/.vim/_backups " store backups here
set directory=~/.vim/_swaps   " store swap files here

